name: Run iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests on iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Available Simulators
        run:  simulators=$(xcrun simctl list devices)

      - name: Run Tests on Specified Simulator
        run: xcodebuild test -scheme BugetManager -destination "platform=iOS Simulator,id=$948EB4DC-22AF-4F28-97AA-160EDC5FB6E2"

      - name: Run Fastlane Tests
        run: fastlane all_tests
