name: Fastlane

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  fastlane:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Bundler
        run: gem install bundler
        env:
          GEM_HOME: ${{github.workspace}}/vendor/bundle
          BUNDLE_PATH: ${{github.workspace}}/vendor/bundle

      - name: Run Fastlane Tests
        run: fastlane all_tests
