name: Run iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests on iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install
        
      - name: Run Fastlane Tests
        run: fastlane all_tests
