name: Run iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests on iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Available Simulators
        run: |
          simulators=$(xcrun simctl list devices)
          echo "$simulators"
          export IOS_SIMULATOR_UUID=$(echo "$simulators" | grep -oE 'iPhone.*?\((.*?)\)' | awk -F'[()]' '{print $2}' | head -n 1)
          echo "Found Simulator UUID: $IOS_SIMULATOR_UUID"

      - name: Run Tests on Specified Simulator
        run: xcodebuild test -scheme BugetManager -destination "platform=iOS Simulator,id=$IOS_SIMULATOR_UUID"

      - name: Run Fastlane Tests
        run: fastlane all_tests
