name: Run iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests on iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create iPhone 14 Pro with iOS 16.2 Simulator
        run: |
          xcrun simctl create "iPhone 14 Pro" com.apple.CoreSimulator.SimDeviceType.iPhone-13-Pro com.apple.CoreSimulator.SimRuntime.iOS-16-2
          export IOS_SIMULATOR_UUID=$(xcrun simctl list devices | grep "iPhone 14 Pro" | awk '{print $3}')
          echo "Found Simulator UUID: $IOS_SIMULATOR_UUID"

      - name: Run Tests on Specified Simulator
        run: xcodebuild test -scheme YourScheme -destination "platform=iOS Simulator,id=$IOS_SIMULATOR_UUID"
        
      - name: Run Fastlane Tests
        run: fastlane all_tests
