name: Fastlane Tests

on:
  push:
    branches:
      - main # Change this to your main branch name
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install

    - name: Run Fastlane tests
      run: bundle exec fastlane tests
